name: Quark Sign-in

on:
  schedule:
    # 每天北京时间凌晨 00:00 自动运行
    - cron: '0 0 * * *'
      timezone: 'Asia/Shanghai'

  # 保留手动运行按钮
  workflow_dispatch:

jobs:
  sign-in:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run Quark Sign-in
        env:
          COOKIE_QUARK: ${{ secrets.COOKIE_QUARK }}
        run: |
          python checkIn_Quark.py
